name: keepalive

on:
  schedule:
    - cron: "*/12 * * * *"   # cada 15 minutos (aún más barato)
  workflow_dispatch: {}       # lanzable a mano

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping /health (diagnóstico barato)
        run: |
          curl -fsS -A "KeepaliveBot/1.0" https://english-coach-ai.onrender.com/health || true
